// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ngrams
CharacterVector ngrams(const CharacterVector terms, uint32_t ngram_min, uint32_t ngram_max, const String sep);
RcppExport SEXP text2vec_ngrams(SEXP termsSEXP, SEXP ngram_minSEXP, SEXP ngram_maxSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const CharacterVector >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type ngram_min(ngram_minSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type ngram_max(ngram_maxSEXP);
    Rcpp::traits::input_parameter< const String >::type sep(sepSEXP);
    __result = Rcpp::wrap(ngrams(terms, ngram_min, ngram_max, sep));
    return __result;
END_RCPP
}
