# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @name ngrams
#' @title Generates ngrams
#' @description Generates ngrams character vector from tokens
#' @param terms input tokens
#' @param ngram_min min number of tokens in ngram
#' @param ngram_max max number of tokens in ngram
#' @param stopwords character vector of stopwords to filter them out
#' @param sep string separator between tokems
ngrams <- function(terms, ngram_min, ngram_max, stopwords = character(), sep = "_") {
    .Call('text2vec_ngrams', PACKAGE = 'text2vec', terms, ngram_min, ngram_max, stopwords, sep)
}

