# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_xptr_unordered_set <- function(x) {
    .Call('text2vec_create_xptr_unordered_set', PACKAGE = 'text2vec', x)
}

collapse_collocations_cpp <- function(docs, xptr_unordered_set, r_sep) {
    .Call('text2vec_collapse_collocations_cpp', PACKAGE = 'text2vec', docs, xptr_unordered_set, r_sep)
}

cpp_glove_create <- function(params) {
    .Call('text2vec_cpp_glove_create', PACKAGE = 'text2vec', params)
}

cpp_glove_get_word_vectors <- function(ptr) {
    .Call('text2vec_cpp_glove_get_word_vectors', PACKAGE = 'text2vec', ptr)
}

cpp_glove_set_cost_zero <- function(ptr) {
    invisible(.Call('text2vec_cpp_glove_set_cost_zero', PACKAGE = 'text2vec', ptr))
}

cpp_glove_partial_fit <- function(ptr, x_irow, x_icol, x_val, iter_order) {
    .Call('text2vec_cpp_glove_partial_fit', PACKAGE = 'text2vec', ptr, x_irow, x_icol, x_val, iter_order)
}

cpp_glove_get_sparsity_level <- function(ptr) {
    .Call('text2vec_cpp_glove_get_sparsity_level', PACKAGE = 'text2vec', ptr)
}

cpp_glove_dump_model <- function(ptr) {
    .Call('text2vec_cpp_glove_dump_model', PACKAGE = 'text2vec', ptr)
}

hasher <- function(x, hash_size) {
    .Call('text2vec_hasher', PACKAGE = 'text2vec', x, hash_size)
}

cpp_hash_corpus_create <- function(size, n_min, n_max, use_signed_hash) {
    .Call('text2vec_cpp_hash_corpus_create', PACKAGE = 'text2vec', size, n_min, n_max, use_signed_hash)
}

cpp_hash_corpus_insert_document_batch <- function(ptr, docs_batch, grow_dtm, context, window_size, weights) {
    invisible(.Call('text2vec_cpp_hash_corpus_insert_document_batch', PACKAGE = 'text2vec', ptr, docs_batch, grow_dtm, context, window_size, weights))
}

cpp_hash_corpus_get_tcm <- function(ptr) {
    .Call('text2vec_cpp_hash_corpus_get_tcm', PACKAGE = 'text2vec', ptr)
}

cpp_hash_corpus_get_dtm <- function(ptr) {
    .Call('text2vec_cpp_hash_corpus_get_dtm', PACKAGE = 'text2vec', ptr)
}

colMins <- function(x) {
    .Call('text2vec_colMins', PACKAGE = 'text2vec', x)
}

colMaxs <- function(x) {
    .Call('text2vec_colMaxs', PACKAGE = 'text2vec', x)
}

rowMins <- function(x) {
    .Call('text2vec_rowMins', PACKAGE = 'text2vec', x)
}

rowMaxs <- function(x) {
    .Call('text2vec_rowMaxs', PACKAGE = 'text2vec', x)
}

euclidean_dist <- function(x, y) {
    .Call('text2vec_euclidean_dist', PACKAGE = 'text2vec', x, y)
}

is_invalid_ptr <- function(sexp_ptr) {
    .Call('text2vec_is_invalid_ptr', PACKAGE = 'text2vec', sexp_ptr)
}

cpp_vocabulary_corpus_create <- function(vocab_R, n_min, n_max, stopwords_R, delim) {
    .Call('text2vec_cpp_vocabulary_corpus_create', PACKAGE = 'text2vec', vocab_R, n_min, n_max, stopwords_R, delim)
}

cpp_vocabulary_corpus_insert_document_batch <- function(ptr, docs_batch, grow_dtm, context, window_size, weights) {
    invisible(.Call('text2vec_cpp_vocabulary_corpus_insert_document_batch', PACKAGE = 'text2vec', ptr, docs_batch, grow_dtm, context, window_size, weights))
}

cpp_vocabulary_corpus_get_tcm <- function(ptr) {
    .Call('text2vec_cpp_vocabulary_corpus_get_tcm', PACKAGE = 'text2vec', ptr)
}

cpp_vocabulary_corpus_get_dtm <- function(ptr) {
    .Call('text2vec_cpp_vocabulary_corpus_get_dtm', PACKAGE = 'text2vec', ptr)
}

cpp_vocab_create <- function(ngram_min, ngram_max, stopwords_R, delim) {
    .Call('text2vec_cpp_vocab_create', PACKAGE = 'text2vec', ngram_min, ngram_max, stopwords_R, delim)
}

cpp_vocabulary_insert_document_batch <- function(ptr, document_batch) {
    invisible(.Call('text2vec_cpp_vocabulary_insert_document_batch', PACKAGE = 'text2vec', ptr, document_batch))
}

cpp_get_vocab_statistics <- function(ptr) {
    .Call('text2vec_cpp_get_vocab_statistics', PACKAGE = 'text2vec', ptr)
}

cpp_get_document_count <- function(ptr) {
    .Call('text2vec_cpp_get_document_count', PACKAGE = 'text2vec', ptr)
}

warplda_create <- function(n_topics, doc_topic_prior, topic_word_prior) {
    .Call('text2vec_warplda_create', PACKAGE = 'text2vec', n_topics, doc_topic_prior, topic_word_prior)
}

warplda_init_dtm <- function(ptr, m, z_old, z_new) {
    invisible(.Call('text2vec_warplda_init_dtm', PACKAGE = 'text2vec', ptr, m, z_old, z_new))
}

warplda_set_topic_word_count <- function(ptr, topic_word_count) {
    invisible(.Call('text2vec_warplda_set_topic_word_count', PACKAGE = 'text2vec', ptr, topic_word_count))
}

run_one_iter <- function(ptr, update_topics = TRUE, calc_ll = TRUE) {
    .Call('text2vec_run_one_iter', PACKAGE = 'text2vec', ptr, update_topics, calc_ll)
}

warplda_get_doc_topic_count <- function(ptr) {
    .Call('text2vec_warplda_get_doc_topic_count', PACKAGE = 'text2vec', ptr)
}

warplda_get_topic_word_count <- function(ptr) {
    .Call('text2vec_warplda_get_topic_word_count', PACKAGE = 'text2vec', ptr)
}

warplda_get_c_all_local <- function(ptr) {
    .Call('text2vec_warplda_get_c_all_local', PACKAGE = 'text2vec', ptr)
}

warplda_get_c_all <- function(ptr) {
    .Call('text2vec_warplda_get_c_all', PACKAGE = 'text2vec', ptr)
}

warplda_set_c_all <- function(ptr, c_all) {
    invisible(.Call('text2vec_warplda_set_c_all', PACKAGE = 'text2vec', ptr, c_all))
}

warplda_reset_c_all_local <- function(ptr) {
    invisible(.Call('text2vec_warplda_reset_c_all_local', PACKAGE = 'text2vec', ptr))
}

